# Generated by Django 2.1.1 on 2018-09-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registraion_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collage_Name', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=500)),
                ('No_Participants', models.IntegerField(max_length=200)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Mobile', models.CharField(max_length=10, null=True)),
                ('Message', models.CharField(max_length=5000, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'website_feedback_database',
                'managed': True,
            },
        ),
    ]
