# Generated by Django 2.1.1 on 2018-09-30 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.CharField(blank='True', max_length=30, null='True')),
                ('post', models.CharField(blank='True', max_length=30, null='True')),
                ('Roll_No', models.CharField(blank='True', max_length=10, null='True')),
                ('phone', models.CharField(blank='True', max_length=10, null='True')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
