# Generated by Django 2.1.1 on 2018-09-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registraion_information',
            old_name='Mobile',
            new_name='Contact',
        ),
        migrations.RemoveField(
            model_name='registraion_information',
            name='Message',
        ),
    ]
