# Generated by Django 2.1.1 on 2018-09-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_auto_20180929_2235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registraion_Information',
            new_name='Registration_Info',
        ),
    ]
