# Generated by Django 2.1.1 on 2018-09-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_auto_20180929_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_info',
            name='No_Participants',
            field=models.IntegerField(),
        ),
    ]
