# Generated by Django 2.1.1 on 2018-10-01 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_auto_20180930_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration_info',
            old_name='Collage_Name',
            new_name='College_Name',
        ),
    ]
