# Generated by Django 2.0.2 on 2018-10-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_auto_20181001_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_info',
            name='Address',
            field=models.TextField(null=True),
        ),
    ]
