# Generated by Django 2.0.2 on 2018-10-02 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_auto_20181001_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration_info',
            old_name='No_Participants',
            new_name='Number_of_Participants',
        ),
    ]
